/**
 * @author zhao
 * @class QH.company.GridToolbar
 * @extends QH.ux.grid.BaseToolbar
 */
QH.company.GridToolbar = Ext.extend(QH.ux.grid.BaseToolbar,{
	objName:'CotCompany',
	tbarModel:'all',
	initComponent:function(){
		this.items = [{
  			xtype:'textfield',
			searchName:'company.companyName',
			isSearchField:true,
			emptyText:'中文名称',
			width:90,
			maxLength:50,
			maxLengthText:'中文名称长度最大不能超过{0}'
 		},{
  			xtype:'textfield',
			searchName:'company.companyNameEn',
			isSearchField:true,
			emptyText:'英文名称',
			width:90,
			maxLength:150,
			maxLengthText:'英文名称长度最大不能超过{0}'
 		},{
  			xtype:'textfield',
			searchName:'company.companyShortName',
			isSearchField:true,
			emptyText:'简称',
			width:90,
			maxLength:50,
			maxLengthText:'简称长度最大不能超过{0}'
 		},{
 			hidden:true,
 			xtype:'textfield',
			searchName:'company.companyCorporation',
			isSearchField:true,
			emptyText:'公司法人',
			width:90,
			maxLength:50,
			maxLengthText:'公司法人长度最大不能超过{0}'
 		},{
 			hidden:true,
 			xtype:'textfield',
			searchName:'company.comapanyAddr',
			isSearchField:true,
			emptyText:'中文地址',
			width:90,
			maxLength:100,
			maxLengthText:'中文地址长度最大不能超过{0}'
 		},{
 			hidden:true,
 			xtype:'textfield',
			searchName:'company.companyAddrEn',
			isSearchField:true,
			emptyText:'英文地址',
			width:90,
			maxLength:100,
			maxLengthText:'英文地址长度最大不能超过{0}'
 		},{
 			hidden:true,
 			xtype:'textfield',
			searchName:'company.companyNbr',
			isSearchField:true,
			emptyText:'公司电话',
			width:90,
			maxLength:100,
			maxLengthText:'公司电话长度最大不能超过{0}'
 		},{
 			hidden:true,
 			xtype:'textfield',
			searchName:'company.companyFax',
			isSearchField:true,
			emptyText:'公司传真',
			width:90,
			maxLength:100,
			maxLengthText:'公司传真长度最大不能超过{0}'
 		},{
 			hidden:true,
 			xtype:'textfield',
			searchName:'company.companyPost',
			isSearchField:true,
			emptyText:'邮编',
			width:90,
			maxLength:20,
			maxLengthText:'邮编长度最大不能超过{0}'
 		},{
 			hidden:true,
 			xtype:'textfield',
			searchName:'company.companyWebSite',
			isSearchField:true,
			emptyText:'公司网址',
			width:90,
			maxLength:100,
			maxLengthText:'公司网址长度最大不能超过{0}'
 		},{
 			hidden:true,
 			xtype:'textfield',
			searchName:'company.companyMail',
			isSearchField:true,
			emptyText:'邮箱',
			width:90,
			maxLength:100,
			maxLengthText:'邮箱长度最大不能超过{0}'
 		},{
 			hidden:true,
 			xtype:'textfield',
			searchName:'company.remark',
			isSearchField:true,
			emptyText:'备注',
			width:90,
			maxLength:200,
			maxLengthText:'备注长度最大不能超过{0}'
 		},{
 			hidden:true,
 			xtype:'textfield',
			searchName:'company.companyLogo',
			isSearchField:true,
			emptyText:'Logo',
			width:90,
			maxLength:200,
			maxLengthText:'Logo长度最大不能超过{0}'
 		},{
			xtype:'searchcombo',
			searchName:'company.identityId',
			store:this.grid.store,
			checkModified:true,
			emptyText:'序列号'
		}];
		QH.company.GridToolbar.superclass.initComponent.call(this);
	}
});
Ext.reg('companytoolbar',QH.company.GridToolbar);
